templates/access_switch.j2
=========================
service timestamps debug datetime msec localtime show-timezone
service timestamps log datetime msec localtime show-timezone
!
hostname {{item[0].hostname}}
!
logging buffered 32000
no logging console
enable secret 0 {{item[0].secret}}
!
!
!
!
interface FastEthernet0/1
 switchport access vlan {{item[0].access_vlan}}
 switchport mode access
 spanning-tree portfast
!
{% for slot in range(1,23) %}
interface {{ item[slot] }}
 switchport access vlan {{item[0].access_vlan}}
 switchport mode access
 spanning-tree portfast
!
!
{% endfor %}
interface FastEthernet0/24
 switchport access vlan {{item[0].access_vlan}}
 switchport mode access
 spanning-tree portfast
!
interface Vlan1
 ip address {{item[0].ip_addr}} 255.255.255.0
 no ip route-cache
!
ip default-gateway {{item[0].default_gateway}}
snmp-server community {{item[0].snmp_community}} RO
{% if item[0].SNMP %}
access-list 98 remark *** SNMP ***
access-list 98 permit any
!
snmp-server view VIEWSTD iso included
snmp-server group READONLY v3 priv read VIEWSTD access 98
snmp-server user pysnmp READONLY v3 auth sha auth_key priv aes 128 encrypt_key
{% endif %}
!
line con 0
line vty 0 4
 login
line vty 5 15
 login
!
!
end


vars/main.yml
=====================
---
test_routers:
  - {hostname: pynet-rtr1, secret: password, ip_addr: 1.1.1.4, default_gateway: 1.1.1.1, access_vlan: 100, SNMP: True, snmp_community: SPECIAL }
  - {hostname: pynet-rtr2, secret: password, ip_addr: 2.2.2.4, default_gateway: 2.2.2.1, access_vlan: 200, SNMP: True, snmp_community: SPECIAL }
  - {hostname: pynet-rtr3, secret: password, ip_addr: 3.3.3.4, default_gateway: 3.3.3.1, access_vlan: 300, SNMP: True, snmp_community: SPECIAL }
  - {hostname: pynet-rtr4, secret: password, ip_addr: 4.4.4.4, default_gateway: 4.4.4.1, access_vlan: 400, SNMP: True, snmp_community: SPECIAL }
  - {hostname: pynet-rtr5, secret: password, ip_addr: 5.5.5.4, default_gateway: 5.5.5.1, access_vlan: 500, SNMP: True, snmp_community: SPECIAL }


tasks/main.yml
============================
---
- name: Generate configuration file
  template: src=access_switch.j2 dest=/home/ohassan/training/class3/ANSIBLE/CFGS/{{item[0].hostname}}.txt
  with_nested:
    - test_routers
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23

site.yml
======================
---
- name: Generate configuration file
  hosts: local

  roles:
    - router
